CSV_FIELDS = {
    "billing/products": [
        "product_id",
        "product_name",
        "product_family",
        "billing_interval",
        "list_price_minor",
        "currency",
        "is_active",
        "created_at",
        "updated_at",
    ],
    "billing/subscriptions": [
        "subscription_id",
        "customer_id",
        "product_id",
        "subscription_status",
        "started_at",
        "cancelled_at",
        "created_at",
        "updated_at",
    ],
    "billing/invoices": [
        "invoice_id",
        "subscription_id",
        "customer_id",
        "product_id",
        "invoice_date",
        "due_date",
        "currency",
        "subtotal_minor",
        "tax_minor",
        "total_minor",
        "invoice_status",
        "created_at",
        "updated_at",
    ],
    "psp/payment_attempts": [
        "payment_attempt_id",
        "invoice_id",
        "provider_customer_id",
        "attempted_at",
        "currency",
        "amount_minor",
        "payment_method_type",
        "status",
        "failure_code",
        "provider_transaction_id",
    ],
    "psp/financial_events": [
        "financial_event_id",
        "event_type",
        "payment_attempt_id",
        "invoice_id",
        "original_capture_id",
        "event_at",
        "currency",
        "amount_minor",
        "provider_transaction_id",
    ],
        "psp/settlements": [
        "settlement_id",
        "settlement_date",
        "settlement_currency",
        "gross_amount_minor",
        "fee_amount_minor",
        "net_payout_minor",
        "status",
        "bank_reference",
        "created_at",
    ],
    "psp/settlement_items": [
        "settlement_item_id",
        "settlement_id",
        "financial_event_id",
        "transaction_currency",
        "transaction_amount_minor",
        "settlement_gross_eur_minor",
        "fee_eur_minor",
        "settlement_net_eur_minor",
        "psp_fx_rate",
    ],
    "bank/statement_transactions": [
        "bank_transaction_id",
        "booking_date",
        "value_date",
        "direction",
        "currency",
        "amount_minor",
        "counterparty",
        "payment_reference",
        "status",
    ],
    "accounting/journal_lines": [
        "journal_line_id",
        "journal_entry_id",
        "posting_date",
        "account_code",
        "account_name",
        "debit_eur_minor",
        "credit_eur_minor",
        "source_system",
        "source_reference_type",
        "source_reference",
        "journal_status",
        "created_at",
    ],
}