CSV_FIELDS = {
    "billing/products": [
        "product_id",
        "product_name",
        "product_family",
        "billing_interval",
        "list_price_minor",
        "currency",
        "is_active",
        "created_at",
        "updated_at",
    ],
    "billing/subscriptions": [
        "subscription_id",
        "customer_id",
        "product_id",
        "subscription_status",
        "started_at",
        "cancelled_at",
        "created_at",
        "updated_at",
    ],
    "billing/invoices": [
        "invoice_id",
        "subscription_id",
        "customer_id",
        "product_id",
        "invoice_date",
        "due_date",
        "currency",
        "subtotal_minor",
        "tax_minor",
        "total_minor",
        "invoice_status",
        "created_at",
        "updated_at",
    ],
    "psp/payment_attempts": [
        "payment_attempt_id",
        "invoice_id",
        "provider_customer_id",
        "attempted_at",
        "currency",
        "amount_minor",
        "payment_method_type",
        "status",
        "failure_code",
        "provider_transaction_id",
    ],
    "psp/financial_events": [
        "financial_event_id",
        "event_type",
        "payment_attempt_id",
        "invoice_id",
        "original_capture_id",
        "event_at",
        "currency",
        "amount_minor",
        "provider_transaction_id",
    ],
}